### ISSUE TITLE
ERROR:  extra data after last expected column

### ISSUE THREAD

**Issue by cigrainger** [altay-oz/load_patstat#1]
I consistently get ERROR:  extra data after last expected column when running the insert script. Example:

_patstat_2015
tls201_appln
tls201
unziping /Volumes/gdrive/zip_patstat_2015/tls201_part01.zip
ERROR:  extra data after last expected column
CONTEXT:  COPY tls201_appln, line 2: "0,"ZZ","","D ",9999-12-31,9999,"","PI",0,9999-12-31,9999,0,9999-12-31,9999,0,0,0,0,0,0,0,0"
STATEMENT:  COPY  tls201_appln FROM STDIN DELIMITER AS ',' CSV HEADER QUOTE AS '"'
ERROR:  extra data after last expected column
CONTEXT:  COPY tls201_appln, line 2: "0,"ZZ","","D ",9999-12-31,9999,"","PI",0,9999-12-31,9999,0,9999-12-31,9999,0,0,0,0,0,0,0,0"
INSERTED /Volumes/gdrive/zip_patstat_2015/tls201_part01.zip
unziping /Volumes/gdrive/zip_patstat_2015/tls201_part02.zip
ERROR:  extra data after last expected column

**Comment by altay-oz** [comment]
Hi,
I used these scripts for the PATSTAT april 2015 version. Which version
are you using? I guess that you are not using april 2015.

I have a copy of a PATSTAT nov 2015 and I can work on that but I don't
have a 2016 copy.

Altay

**Comment by trigrano** [comment]
cigraigner, just read your comment while trying to load Patstat autumn 2016 into a postgres server. Could you already solve the issue?
THX, 
trigrano
